name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey! I see that this is your first issue resolve. That is great! Welcome!'
        pr-message: 'Hey! I see that this is your first PR. That is great! Welcome!'
